# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sujilee <sujilee@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/28 16:23:20 by sujilee           #+#    #+#              #
#    Updated: 2022/03/28 16:24:23 by sujilee          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #



SRCS := Contact.cpp PhoneBook.cpp main.cpp

CPP := c++
CFLAGS := -Wall -Wextra -Werror -std=c++98

NAME := PhoneBook

$(NAME): $(SRCS)
	$(CPP) $(FLAG) -o $(NAME) $(SRCS)

all: $(NAME)

clean:
	rm -f $(NAME)

re: clean all

.PHONY: all clean re